############################ Copyrights and license ###########################
#                                                                             #
# Copyright 2025 Brian Gray <bgraymusic@gmail.com>                            #
#                                                                             #
# This file is part of GitHubGQL.                                             #
# https://github.com/bgraymusic/github-gql                                    #
#                                                                             #
# GitHubGQL is free software: you can redistribute it and/or modify it under  #
# the terms of the GNU Lesser General Public License as published by the Free #
# Software Foundation, either version 3 of the License, or (at your option)   #
# any later version.                                                          #
#                                                                             #
# GitHubGQL is distributed in the hope that it will be useful, but WITHOUT    #
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or       #
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License #
# for more details.                                                           #
#                                                                             #
# You should have received a copy of the GNU Lesser General Public License    #
# along with PyGithub. If not, see <http://www.gnu.org/licenses/>.            #
#                                                                             #
###############################################################################

github_graphql_endpoint: https://api.github.com/graphql
github_graphql_schema: schema.docs.graphql

# Default fields by interface
interfaces:
  Actor: [login, url]
  Comment: [author, createdAt, id]
  Contribution: [occurredAt, url, user]
  EnterpriseAuditEntryData: [enterpriseUrl]
  GitObject: [commitUrl, id, oid]
  GitSignature: [email, signer, state]
  Migration: [createdAt, id, state]
  Node: [id]
  OauthApplicationAuditEntryData: [oauthApplicationName, oauthApplicationUrl]
  PackageOwner: [id]
  ProfileOwner: [email, id, login, name, websiteUrl]
  ProjectV2FieldCommon: [createdAt, id, name]
  ProjectV2ItemFieldValueCommon: [createdAt, id]
  ProjectV2Owner: [id]
  Reactable: [id]
  RepositoryAuditEntryData: [repositoryUrl]
  RepositoryInfo: [createdAt, homepageUrl, nameWithOwner, url]
  RepositoryOwner: [id, login, url]
  Starrable: [id]
  Subscribable: [id]
  SubscribableThread: [id]
  TeamAuditEntryData: [teamName, teamUrl]
  TopicAuditEntryData: [topicName]
  UniformResourceLocatable: [url]

# To merge across pages, objects need some kind of identifier to match on.
# Usually we use 'id', but some types do not have that field. Here we
# designate what field(s) to use for matching.
no_id_types:
  BranchProtectionRuleConflict: NA
  CheckAnnotation: NA
  CheckStep: NA
  CreatedCommitContribution: NA
  CreatedIssueContribution: NA
  CreatedPullRequestContribution: NA
  CreatedPullRequestReviewContribution: NA
  CreatedRepositoryContribution: NA
  DependencyGraphDependency: NA
  DeploymentProtectionRule: NA
  DeploymentReques: NAt
  GitActor: NA
  ProjectV2ItemFieldValue: NA
  ProjectV2SortBy: NA
  ProjectV2SortByField: NA
  PullRequestChangedFile: NA
  PullRequestTimelineItems: NA
  SecurityVulnerability: NA
  SocialAccount: url
  SponsorAndLifetimeValue: NA
  Submodule: NA
