name: On Release Created

on: create # does not support filtering by type (tag), must do later

defaults:
  run:
    shell: bash -v {0}

jobs:
  publish-to-pypi:
    if: github.event.ref_type == 'tag' # create can be branches or tags; we want only tags
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
